<?php if (\App\Core\Access::hasRole('super_admin')) { ?>

<section class="cards-grid">
    <a href="/stockeasy/public/index.php?route=log-modif" class="card">
        <div class="card__icon">
            <i class="fa-solid fa-file-pen"></i>
        </div>
        <p class="card__text">Modification Logs</p>
    </a>

    <a href="/stockeasy/public/index.php?route=log-sys" class="card">
        <div class="card__icon">
            <i class="fa-solid fa-file-shield"></i>
        </div>
        <p class="card__text">System Logs</p>
    </a>
</section>

<?php } ?>