<main class="container">
    <section class="cards-grid">
        
        <a href="/stockeasy/public/index.php?route=stock-home" class="card">
            <div class="card__icon">
                <i class="fa-solid fa-cubes"></i>
            </div>
            <p class="card__text">Stock</p>
        </a>

        <a href="/stockeasy/public/index.php?route=construction" class="card">
            <div class="card__icon">
                <i class="fa-solid fa-address-book"></i>
            </div>
            <p class="card__text">Clients</p>
        </a>

        <a href="/stockeasy/public/index.php?route=construction" class="card">
            <div class="card__icon">
                <i class="fa-solid fa-calculator"></i>
            </div>
            <p class="card__text">Compta</p>
        </a>

        <a href="/stockeasy/public/index.php?route=construction" class="card">
            <div class="card__icon">
                <i class="fa-solid fa-print"></i>
            </div>
            <p class="card__text">Editions</p>
        </a>

        <a href="/stockeasy/public/index.php?route=user-home" class="card">
            <div class="card__icon">
                <i class="fa-solid fa-users-viewfinder"></i>
            </div>
            <p class="card__text">Gestion des utilisateurs</p>
        </a>

        <a href="/stockeasy/public/index.php?route=log-home" class="card">
            <div class="card__icon">
                <i class="fa-solid fa-database"></i>
            </div>
            <p class="card__text">Gestion des logs</p>
        </a>

    </section>
</main>