<section class="page">
    <h1 class="sr-only">Erreur 404 - Page introuvable</h1>
    <div class="error">
        <img src="/stockeasy/public/assets/img/img404.webp" alt="Illustration d'une barrière de chantier avec un panneau 404 et un pneu crevé devant, indiquant une page introuvable sur StockEasy" class="error__img">
        <a href="/stockeasy/public/index.php?route=home" class="error__link">
            <i class="fa-solid fa-hand-point-left" aria-hidden="true"></i> 
            Retour à l'accueil
        </a>
    </div>
</section>
