<section class="cards-grid">
    <a href="/stockeasy/public/index.php?route=customer-create" class="card">
        <div class="card__icon">
            <i class="fa-solid fa-user-plus"></i>
        </div>
        <p class="card__text">Nouveau client</p>
    </a>

    <a href="/stockeasy/public/index.php?route=customer-search" class="card">
        <div class="card__icon">
            <i class="fa-solid fa-user-pen"></i>
        </div>
        <p class="card__text">Rechercher & Modifier</p>
    </a>
</section>