<section class="cards-grid">
    <h2 class="sr-only">Navigation clients</h2>
    <a href="/stockeasy/public/index.php?route=customer-create" class="card" aria-label="Accéder à la création d’un nouveau client">
        <div class="card__icon">
            <i class="fa-solid fa-user-plus" aria-hidden="true"></i>
        </div>
        <p class="card__text">Nouveau client</p>
    </a>

    <a href="/stockeasy/public/index.php?route=customer-search" class="card" aria-label="Accéder à la recherche et à la modification des clients">
        <div class="card__icon">
            <i class="fa-solid fa-user-pen" aria-hidden="true"></i>
        </div>
        <p class="card__text">Rechercher & Modifier</p>
    </a>
</section>