<section class="cards-grid">
    <a href="/stockeasy/public/index.php?route=user-create" class="card">
        <div class="card__icon">
            <i class="fa-solid fa-user-plus"></i>
        </div>
        <p class="card__text">Création</p>
    </a>

    <a href="/stockeasy/public/index.php?route=user-list&status=active" class="card">
        <div class="card__icon">
            <i class="fa-solid fa-users"></i>
        </div>
        <p class="card__text">Utilisateurs actifs</p>
    </a>

    <a href="/stockeasy/public/index.php?route=user-list&status=inactive" class="card">
        <div class="card__icon">
            <i class="fa-solid fa-users-slash"></i>
        </div>
        <p class="card__text">Utilisateurs inactifs</p>
    </a>

    <a href="/stockeasy/public/index.php?route=user-role" class="card">
        <div class="card__icon">
            <i class="fa-solid fa-user-shield"></i>
        </div>
        <p class="card__text">Rôles</p>
    </a>

    <a href="/stockeasy/public/index.php?route=user-permission" class="card">
        <div class="card__icon">
            <i class="fa-solid fa-user-gear"></i>
        </div>
        <p class="card__text">Permissions par utilisateurs</p>
</a>
</section>