<section class="cards-grid">
    <h2 class="sr-only">Navigation stock</h2>

    <?php if (\App\Core\Access::hasOneRole(['super_admin', 'admin', 'secretary', 'user'])) { ?>
        <a href="/stockeasy/public/index.php?route=stock-create" class="card">
            <div class="card__icon">
                <i class="fa-solid fa-file-pen"></i>
            </div>
            <p class="card__text">Création</p>
        </a>
    <?php } ?>

    <?php if (\App\Core\Access::hasOneRole(['super_admin', 'admin', 'secretary', 'user', 'intern'])) { ?>
        <a href="/stockeasy/public/index.php?route=stock-search" class="card">
            <div class="card__icon">
                <i class="fa-solid fa-magnifying-glass"></i>
            </div>
            <p class="card__text">Recherche</p>
        </a>

        <a href="/stockeasy/public/index.php?route=stock-list" class="card">
            <div class="card__icon">
                <i class="fa-solid fa-table-list"></i>
            </div>
            <p class="card__text">Inventaire</p>
        </a>
    <?php } ?>

</section>
