<div class="page stock-list">
    <h1 class="page__title">Inventaire</h1>
    <p class="stock-list__count">
        <em>Résultat(s) :
        <span class="result-count"><?= htmlspecialchars($nbDisplayed, ENT_QUOTES) ?></span>
        / <?= htmlspecialchars($nbTotal, ENT_QUOTES) ?>
        </em>
    </p>
    <div class="page__wrapper">
        <div class="stock-list__filter">
            <?php
                $stockFilters = [
                    'all' => 'Tout le stock',
                    'in'  => 'En stock',
                    'out' => 'Rupture de stock'
                ];
            ?>
            <form method="GET" action="index.php" class="stock-list__form form">
                <input type="hidden" name="route" class="form__input" value="stock-list" />

                <fieldset class="form__fieldset stock-list__fieldset">
                    <legend class="form__legend">Choix du stock à afficher</legend>
                    <div class="stock-list__radios">
                        <?php foreach ($stockFilters as $value => $label) { ?>
                            <div class="stock-list__radio">
                                <input type="radio" id="<?= $value ?>Stock" name="stockFilter" class="form__input" value="<?= $value ?>" <?= ($filter === $value) ? 'checked' : '' ?> />
                                <label class="form__label" for="<?= $value ?>Stock"><?= $label ?></label>
                            </div>
                        <?php } ?>
                    </div>
                </fieldset>

                <button class="stock-list__actions btn btn--icon" type="submit" aria-label="Voir les résultats">
                    <i class="fa-solid fa-magnifying-glass" aria-hidden="true"></i>
                </button>
            </form>

            <a href="index.php?route=stock-print" target="_blank" class="btn btn--icon" role="button" id="print-btn" aria-label="Imprimer l’inventaire complet">
                <i class="fa-solid fa-print" aria-hidden="true"></i>
            </a>
        </div>

        <section class="stock-page__table-wrapper stock-listing">
            <h2 class="sr-only">Liste des résultats du stock</h2>
            <table class="table">
                <caption class="sr-only">Inventaire des pneus selon le filtre choisi précédemment</caption>
                <thead class="table__thead">
                    <tr class="table__tr">
                        <th class="table__th" scope="col">Marque</th>
                        <th class="table__th" scope="col">Dimensions</th>
                        <th class="table__th" scope="col">Charge / Vitesse</th>
                        <th class="table__th" scope="col">Saison</th>
                        <th class="table__th" scope="col">État</th>
                        <th class="table__th" scope="col">Quantité</th>
                        <th class="table__th" scope="col">Prix unitaire H.T.</th>
                    </tr>
                </thead>
                <tbody>
                <?php foreach($data as $key => $value) { ?>
                    <tr class="table__tr">
                        <td class="table__td" data-label="Marque"><?= htmlspecialchars($value['brand'], ENT_QUOTES) ?></td>
                        <td class="table__td" data-label="Dimensions"><?= htmlspecialchars($value['width'], ENT_QUOTES) ?>/<?= htmlspecialchars($value['height'], ENT_QUOTES) ?>/<?= htmlspecialchars($value['diameter'], ENT_QUOTES) ?></td>
                        <td class="table__td" data-label="Charge/Vitesse"><?= htmlspecialchars($value['load_index'], ENT_QUOTES) ?><?= htmlspecialchars($value['speed_index'], ENT_QUOTES) ?></td>
                        <td class="table__td" data-label="Saison"><?= htmlspecialchars($value['season'], ENT_QUOTES) ?></td>
                        <td class="table__td" data-label="État"><?= htmlspecialchars($value['quality'], ENT_QUOTES) ?></td>
                        <td class="table__td" data-label="Quantité"><?= htmlspecialchars($value['quantity_available'], ENT_QUOTES) ?></td>
                        <td class="table__td" data-label="Prix HT"><?= htmlspecialchars($value['unit_price_excluding_tax'], ENT_QUOTES) ?> €</td>
                    </tr>
                <?php } ?>
                </tbody>
            </table>
            <div class="stock-list__actions">
                <button type="button" class="btn btn--saffron stock-list__load-more" id="load-more" aria-label="Charger plus de résultats">Charger plus...</button>
                <button type="button" class="btn btn--saffron stock-list__load-all" id="load-all" aria-label="Charger tout le stock">Charger tout</button>
            </div>
        </section>
    </div>
</div>